# Generated by Django 5.2.17 on 2026-09-19 10:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
        ('specialties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('appointment_date', models.DateField()),
                ('session', models.CharField(choices=[('MORNING', 'Buổi sáng'), ('AFTERNOON', 'Buổi chiều')], max_length=20)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('CONFIRMED', 'Đã xác nhận'), ('IN_PROGRESS', 'Đang khám'), ('COMPLETED', 'Hoàn tất'), ('CANCELLED', 'Đã hủy')], default='CONFIRMED', max_length=30)),
                ('cancellation_reason', models.CharField(blank=True, choices=[('PATIENT_REQUEST', 'Khách hàng yêu cầu'), ('CLINIC', 'Phòng khám hủy'), ('NO_SHOW', 'Khách không đến')], default='', max_length=30)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_appointments', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='patients.patient')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='specialties.specialty')),
            ],
            options={
                'ordering': ['-appointment_date', '-created_at'],
                'indexes': [models.Index(fields=['appointment_date'], name='ix_appointments_date'), models.Index(fields=['doctor', 'appointment_date'], name='ix_appointments_doctor_date'), models.Index(fields=['patient', 'appointment_date'], name='ix_appointments_patient_date'), models.Index(fields=['status', 'appointment_date'], name='ix_appointments_status_date'), models.Index(fields=['specialty', 'appointment_date'], name='ix_appointments_specialty_date')],
                'constraints': [models.CheckConstraint(condition=models.Q(('session__in', ['MORNING', 'AFTERNOON'])), name='appointments_session_valid'), models.CheckConstraint(condition=models.Q(('status__in', ['CONFIRMED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED'])), name='appointments_status_valid'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'CANCELLED'), models.Q(('cancellation_reason', ''), _negated=True)), models.Q(('status', 'CANCELLED'), _negated=True), _connector='OR'), name='appointments_cancel_reason_required')],
            },
        ),
    ]
